import streamlit as st


st.set_page_config(layout="wide", page_icon = "💪")

st.title("Some of the sources that I used for this project:")

st.markdown("1- https://data.ibb.gov.tr/")
st.markdown("2- https://www.nufusu.com/ilceleri/istanbul-ilceleri-nufusu")
st.markdown("3- https://github.com/ozanyerli/istanbul-districts-geojson")
st.markdown("4- https://medium.com/@saadjansari/customer-segmentation-for-marketing-strategy-tutorial-46db74237532")
st.markdown("5- https://osmnx.readthedocs.io/en/stable/osmnx.html")
st.markdown("6- https://www.youtube.com/watch?v=LRmYjyHk94U&list=PLyLTdapdw7SMiPgcd2YtK-VP3oynlOj29&ab_channel=AutomatingGIS-processes")
st.markdown("7- https://towardsdatascience.com/k-means-clustering-algorithm-applications-evaluation-methods-and-drawbacks-aa03e644b48a#:~:text=Kmeans%20clustering%20is%20one%20of,into%20distinct%20non%2Doverlapping%20subgroups.")
st.markdown("8- https://dzone.com/articles/kmeans-silhouette-score-explained-with-python-exam#:~:text=Silhouette%20score%20is%20used%20to,each%20sample%20of%20different%20clusters.")
st.markdown("9- https://plotly.com/python-api-reference/generated/plotly.express.line.html")
st.markdown("10- https://plotly.com/python/figure-labels/")
st.markdown("11- https://python-visualization.github.io/folium/quickstart.html")
st.markdown("12- https://github.com/randyzwitch/streamlit-folium")
st.markdown("13- https://github.com/python-visualization/folium/blob/main/examples/MarkerCluster.ipynb")
st.markdown("14- https://www.datasciencearth.com/folium-ile-harita-gorsellestirme/")
st.markdown("15- https://medium.com/geekculture/three-ways-to-plot-choropleth-map-using-python-f53799a3e623")
st.markdown("16-https://towardsdatascience.com/retrieving-openstreetmap-data-in-python-1777a4be45bb")
st.markdown("17- https://towardsdatascience.com/shortest-path-algorithm-used-in-osm-street-network-33e0f864f34b")
st.markdown("18- https://towardsdatascience.com/visualising-the-classification-power-of-data-54f5273f640")
st.markdown("19-https://towardsdatascience.com/driving-distance-between-two-or-more-places-in-python-89779d691def#1c17")
st.markdown("20- https://towardsdatascience.com/finding-distance-between-two-latitudes-and-longitudes-in-python-43e92d6829ff")
st.markdown("21- https://towardsdatascience.com/visualization-in-python-finding-routes-between-points-2d97d4881996")
st.markdown("22- https://towardsdatascience.com/driving-distance-between-two-or-more-places-in-python-89779d691def#1c17")
st.markdown("23- https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.explore.html")
st.markdown("24- https://github.com/caniban/MEU_Veri_Bilimi/tree/main/unite%2013%20cografi%20veri%20analizi/01%20geopandas%20kutuphanesi")
st.markdown("25- https://www.youtube.com/watch?v=6eODRAN2w6I")
st.markdown("26- https://geopandas.org/en/stable/gallery/")
st.markdown("27- https://www.youtube.com/watch?v=cFa-AAVPZpg&list=PLGVmvVNxdo90Tq-jHcHOhot_mi8wjp-kn&index=17")
st.markdown("28- https://towardsdatascience.com/geopandas-101-plot-any-data-with-a-latitude-and-longitude-on-a-map-98e01944b972")
st.markdown("29- https://letslearndatasciencetogether.medium.com/pythonda-harita-g%C3%B6rselle%C5%9Ftirmesi-i%CC%87%C3%A7in-geopandas-k%C3%BCt%C3%BCphanesi-52787dec2a3a")
st.markdown("30-https://streamlit.io/")
st.markdown("31- https://discuss.streamlit.io/t/importerror-missing-optional-dependency-xlrd-install-xlrd-1-0-0-for-excel-support-use-pip-or-conda-to-install-xlrd/10538/8")
st.markdown("32- https://discuss.streamlit.io/t/filenotfounderror-errno-2-dot-not-found-in-path/23782/7")
st.markdown("33- https://discuss.streamlit.io/t/uploading-csv-and-excel-files/10866/3")
st.markdown("34- https://discuss.streamlit.io/t/include-an-existing-html-file-in-streamlit-app/5655/3")
st.markdown("35- https://discuss.streamlit.io/t/how-to-render-already-prepared-html-code-with-streamlit/3387/4")
st.markdown("36- https://docs.streamlit.io/library/api-reference/layout/st.tabs")
st.markdown("37- https://docs.streamlit.io/library/api-reference/layout/st.expander")
st.markdown("38- https://www.projectpro.io/recipes/display-code-web-app-streamlit")
st.markdown("39- https://streamlit.io/components?category=visualization")
st.markdown("40- https://discuss.streamlit.io/t/how-to-show-local-gif-image/3408/9")
st.markdown("41- https://docs.streamlit.io/library/api-reference/data/st.json")
st.markdown("42- https://www.youtube.com/watch?v=YfFEFBulFrg&ab_channel=JCharisTech")
st.markdown("43- https://discuss.streamlit.io/t/how-to-show-local-gif-image/3408/7")
st.markdown("44- https://www.researchgate.net/figure/PCA-score-plots-as-2D-A-and-3D-B-OPLS-score-plot-2D-C-and-3D-D-derived_fig3_46281548")
st.markdown("45- https://www.freecodecamp.org/news/python-read-json-file-how-to-load-json-from-a-file-and-parse-dumps/")
st.markdown("46- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.interpolate.html")
st.markdown("47- https://pandas.pydata.org/docs/reference/api/pandas.concat.html")
  
